version: '3'

services: 
    web:
        build: .
        command: python profiles_project/manage.py runserver 0.0.0.0:8000
        image : python3.5
        volumes: 
            - .:/code
        ports: 
            - "8001:8000"
