CREATE DATABASE "person";
CREATE DATABASE "person-test";

\c bill-one-invoice
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO recipient;
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT USAGE ON SCHEMAS TO recipient;

\c bill-one-invoice-test
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO recipient;
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT USAGE ON SCHEMAS TO recipient;