# Generated by Django 2.2.6 on 2020-02-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0003_auto_20200219_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='favoritecommand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Company'),
        ),
    ]
