# Generated by Django 2.2.6 on 2020-02-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_auto_20200216_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecommand',
            name='company',
            field=models.TextField(max_length=255),
        ),
    ]
