version: '3'

services:
  nginx:
    image: nginx:latest
    container_name : django-nginx-centos
    ports:
      - 8000:8000
    volumes:
      - ./service:/service
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres:latest
    container_name : django-postgres-centos
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build: ./service
    image : django-web-centos
    container_name : django-web-api-centos
    command: pipenv run start
    volumes:
      - ./service:/service
    ports:
        - "8000"
    depends_on:
        - db