version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  webs:
    build: ./service
    command: pipenv run start
    image : lynx-redhat
    volumes:
      - ./service:/service
    ports:
        - "8000:8000"
    depends_on:
        - db