# Generated by Django 2.2.6 on 2020-02-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecommand',
            name='previous',
        ),
        migrations.AddField(
            model_name='favoritecommand',
            name='previous_period',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
